# Single layer

In [66]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module): # "Model" inherits from nn.Module
  def __init__(self, num_features):
    super(Model, self).__init__() # incvoking the constructor of the parent class

    self.layer1 = nn.Linear(num_features, 1) # takes num_features as input and produces a single output.
    self.sigmoid = nn.Sigmoid() # creates a sigmoid activation function

  def forward(self, features):
    out = self.layer1(features) # z = wx + b
    out = self.sigmoid(out) # sigmoid(z)
    return out

In PyTorch, calling the model instance like a function (e.g., model(features)) is a shorthand for calling the forward method (e.g., model.forward(features)). Both achieve the same thing - passing the input data through the model's layers and getting the result.

In [67]:
# create dataset
features = torch.randn(10, 5) # 10 samples, 5 features

In [68]:
# create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.2473],
        [0.4587],
        [0.6007],
        [0.2996],
        [0.7103],
        [0.7517],
        [0.3623],
        [0.4933],
        [0.7182],
        [0.2912]], grad_fn=<SigmoidBackward0>)

In [69]:
# weights
model.layer1.weight

Parameter containing:
tensor([[-0.2831,  0.0689, -0.2526,  0.4348,  0.3927]], requires_grad=True)

In [70]:
# bias
model.layer1.bias

Parameter containing:
tensor([-0.3462], requires_grad=True)

In [71]:
!pip install torchinfo

In [72]:
# visualizing
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Multi layer

In [73]:
class Model2(nn.Module):
  def __init__(self, num_features):
    super(Model2, self).__init__()

    self.layer1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.layer1(features)
    out = self.relu(out)
    out = self.layer2(out)
    out = self.sigmoid(out)
    return out

In [74]:
model2 = Model2(features.shape[1])

model2(features)

tensor([[0.3818],
        [0.3804],
        [0.3363],
        [0.4153],
        [0.3644],
        [0.4153],
        [0.3226],
        [0.3835],
        [0.3270],
        [0.4153]], grad_fn=<SigmoidBackward0>)

In [75]:
summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential container

In [76]:
class Model3(nn.Module):
  def __init__(self, num_features):
    super(Model3, self).__init__()

    self.net = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.net(features)
    return out

In [77]:
model3 = Model3(features.shape[1])

model3(features)

tensor([[0.5072],
        [0.5946],
        [0.5696],
        [0.5181],
        [0.5840],
        [0.4742],
        [0.6121],
        [0.5613],
        [0.5950],
        [0.5115]], grad_fn=<SigmoidBackward0>)

# Improving the pipeline
1. Building neural network using nn module
2. Using built-in activation function
3. Using built-in loss function
4. Using built-in optimizer



In [78]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [80]:
df.shape

(569, 33)

In [81]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [82]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [83]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('diagnosis', axis=1), df['diagnosis'], test_size=0.2, random_state=42)

In [84]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [85]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [86]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [87]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [88]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [89]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [90]:
X_train_tensor.shape

torch.Size([455, 30])

In [91]:
X_train_tensor.dtype

torch.float32

In [92]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super(MySimpleNN, self).__init__()

    self.layer1 = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.layer1(features)
    out = self.sigmoid(out)
    return out

In [93]:
learning_rate = 0.1
epochs = 25

In [94]:
# built in loss function
loss_function = nn.BCELoss()

In [95]:
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1)) #view(efficient for contiguous data) is similar to reshape

  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.5918375253677368
Epoch 2, Loss: 0.4616398215293884
Epoch 3, Loss: 0.3894996643066406
Epoch 4, Loss: 0.3440725803375244
Epoch 5, Loss: 0.31264668703079224
Epoch 6, Loss: 0.2894214391708374
Epoch 7, Loss: 0.2714150547981262
Epoch 8, Loss: 0.25694456696510315
Epoch 9, Loss: 0.2449886053800583
Epoch 10, Loss: 0.2348908931016922
Epoch 11, Loss: 0.22621020674705505
Epoch 12, Loss: 0.21863828599452972
Epoch 13, Loss: 0.21195311844348907
Epoch 14, Loss: 0.20599035918712616
Epoch 15, Loss: 0.20062555372714996
Epoch 16, Loss: 0.19576263427734375
Epoch 17, Loss: 0.19132599234580994
Epoch 18, Loss: 0.1872553527355194
Epoch 19, Loss: 0.18350185453891754
Epoch 20, Loss: 0.18002557754516602
Epoch 21, Loss: 0.17679329216480255
Epoch 22, Loss: 0.17377729713916779
Epoch 23, Loss: 0.1709541380405426
Epoch 24, Loss: 0.16830387711524963
Epoch 25, Loss: 0.16580933332443237


In [96]:
model.layer1.weight

Parameter containing:
tensor([[ 0.1114,  0.1187,  0.1505,  0.1189,  0.0520,  0.2155,  0.1285,  0.1855,
          0.0523, -0.1930,  0.3195,  0.1034,  0.2006,  0.3131, -0.0676,  0.0530,
          0.0969, -0.0824, -0.0755, -0.1835,  0.3685,  0.1914,  0.3018,  0.1623,
          0.2886,  0.0632,  0.2973,  0.3956,  0.2431, -0.0080]],
       requires_grad=True)

In [97]:
model.layer1.bias

Parameter containing:
tensor([-0.3021], requires_grad=True)

In [98]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5301631093025208
