In [112]:
import torch
print(torch.__version__)

2.5.1+cu124


In [113]:
if torch.cuda.is_available():
    print("CUDA is available.")
    print("Number of GPUs:", torch.cuda.device_count())
    print("GPU Name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")

CUDA is available.
Number of GPUs: 1
GPU Name: Tesla T4


#Creating Tensors

In [114]:
#using empty
x = torch.empty(5, 3)
print(x)

tensor([[2.3453e-33, 0.0000e+00, 2.2834e-33],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.8664e-44]])


In [115]:
type(x)

torch.Tensor

In [116]:
#using zeros
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [117]:
#using ones
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [118]:
#using rand
x = torch.rand(5, 3)
print(x)

tensor([[0.0041, 0.1088, 0.1637],
        [0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653],
        [0.2979, 0.8035, 0.3813],
        [0.7860, 0.1115, 0.2477]])


In [119]:
#using seed
torch.manual_seed(42)
x = torch.rand(5, 3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])


In [120]:
#using tensor
x = torch.tensor([[5.5, 3], [2, 3]])
print(x)

tensor([[5.5000, 3.0000],
        [2.0000, 3.0000]])


In [121]:
#using arange
x = torch.arange(0, 18, 2).reshape(3, 3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [122]:
#using linespace
x = torch.linspace(0, 18, 12).reshape(3, 4)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])


In [123]:
#using eye
x = torch.eye(5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [124]:
#using full
x = torch.full((5, 3), 3.14159)
print(x)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


#Tensor Shape

In [125]:
x = torch.tensor([[5, 3], [2, 3]])
x.shape

torch.Size([2, 2])

In [126]:
torch.empty_like(x)

tensor([[          37825,      4294967296],
        [      155380672, 137839403707072]])

In [127]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0]])

In [128]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1]])

In [129]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4294, 0.8854],
        [0.5739, 0.2666]])

#Tensor Data Type

In [130]:
x.dtype

torch.int64

In [131]:
#asign data type
x = torch.tensor([[5, 3], [2, 3]], dtype=torch.float16)
x.dtype

torch.float16

In [132]:
#using to
x = x.to(torch.float32)
x.dtype

torch.float32

#Mathematical Operation

###1. Scalar operation

In [133]:
x = torch.rand(2, 2)
x

tensor([[0.6274, 0.2696],
        [0.4414, 0.2969]])

In [134]:
#addition
x + 2

tensor([[2.6274, 2.2696],
        [2.4414, 2.2969]])

In [135]:
#subtraction
x - 2

tensor([[-1.3726, -1.7304],
        [-1.5586, -1.7031]])

In [136]:
#multiplication
x * 2

tensor([[1.2549, 0.5393],
        [0.8827, 0.5938]])

In [137]:
#division
x / 2

tensor([[0.3137, 0.1348],
        [0.2207, 0.1485]])

In [138]:
#mod
x % 2

tensor([[0.6274, 0.2696],
        [0.4414, 0.2969]])

In [139]:
#power
x ** 2

tensor([[0.3937, 0.0727],
        [0.1948, 0.0882]])

###2. Element wise operator

In [140]:
y = torch.rand(2, 2)
y

tensor([[0.8317, 0.1053],
        [0.2695, 0.3588]])

In [141]:
#addition
torch.add(x, y)

tensor([[1.4591, 0.3749],
        [0.7109, 0.6557]])

In [142]:
x + y

tensor([[1.4591, 0.3749],
        [0.7109, 0.6557]])

In [143]:
#subtraction
torch.sub(x, y)

tensor([[-0.2042,  0.1643],
        [ 0.1719, -0.0619]])

In [144]:
x - y

tensor([[-0.2042,  0.1643],
        [ 0.1719, -0.0619]])

In [145]:
#multiplication
torch.mul(x, y)

tensor([[0.5218, 0.0284],
        [0.1189, 0.1065]])

In [146]:
x * y

tensor([[0.5218, 0.0284],
        [0.1189, 0.1065]])

In [147]:
#division
torch.div(x, y)

tensor([[0.7544, 2.5602],
        [1.6377, 0.8275]])

In [148]:
x / y

tensor([[0.7544, 2.5602],
        [1.6377, 0.8275]])

In [149]:
#mod
torch.remainder(x, y)

tensor([[0.6274, 0.0590],
        [0.1719, 0.2969]])

In [150]:
x % y

tensor([[0.6274, 0.0590],
        [0.1719, 0.2969]])

In [151]:
a = torch.tensor([1, -2, 3, -4])

In [152]:
#abs
torch.abs(a)

tensor([1, 2, 3, 4])

In [153]:
#negative
torch.neg(a)

tensor([-1,  2, -3,  4])

In [154]:
b = torch.tensor([1.1, 2.2, 3.7, 4.4])

In [155]:
#round
torch.round(b)

tensor([1., 2., 4., 4.])

In [156]:
#celi
torch.ceil(b)

tensor([2., 3., 4., 5.])

In [157]:
#floor
torch.floor(b)

tensor([1., 2., 3., 4.])

In [158]:
#clamp
torch.clamp(b, min=2, max=3)

tensor([2.0000, 2.2000, 3.0000, 3.0000])

###3. Reduction operator

In [159]:
c = torch.randint(0, 10, (3, 3))
c

tensor([[9, 7, 9],
        [2, 0, 5],
        [9, 3, 4]])

In [160]:
#sum
torch.sum(c)

tensor(48)

In [161]:
torch.sum(c, dim=0)

tensor([20, 10, 18])

In [162]:
torch.sum(c, dim=1)

tensor([25,  7, 16])

In [163]:
#mean
torch.mean(c.float())

tensor(5.3333)

In [164]:
torch.mean(c.float(), dim=0)

tensor([6.6667, 3.3333, 6.0000])

In [165]:
#median
torch.median(c.float())

tensor(5.)

In [166]:
#max & min
torch.max(c)

tensor(9)

In [167]:
#product
torch.prod(c)

tensor(0)

In [168]:
#standard deviation
torch.std(c.float())

tensor(3.3541)

In [169]:
#variance
torch.var(c.float())

tensor(11.2500)

In [170]:
#argmax
torch.argmax(c)

tensor(0)

In [171]:
#argmin
torch.argmin(c)

tensor(4)

###4.Matrix operation

In [172]:
d = torch.randint(0, 10, (2, 3))
e = torch.randint(0, 10, (3, 2))
print(d)
print(e)

tensor([[9, 6, 2],
        [0, 6, 2]])
tensor([[7, 9],
        [7, 3],
        [3, 4]])


In [173]:
#matrix multiplication
torch.mm(d, e)

tensor([[111, 107],
        [ 48,  26]])

In [174]:
#dot product
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

In [175]:
#transpose
torch.t(d)

tensor([[9, 0],
        [6, 6],
        [2, 2]])

In [176]:
#determinant
torch.det(torch.tensor([[1, 2], [3, 4]], dtype=torch.float32))

tensor(-2.)

In [177]:
#inverse
torch.inverse(torch.tensor([[1, 2], [3, 4]], dtype=torch.float32))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

###5.Comparision operation

In [178]:
i = torch.randint(0, 10, (2, 2))
j = torch.randint(0, 10, (2, 2))
print(i)
print(j)

tensor([[3, 7],
        [0, 9]])
tensor([[0, 9],
        [6, 9]])


In [179]:
#greater than
i > j

tensor([[ True, False],
        [False, False]])

In [180]:
#less than
i < j

tensor([[False,  True],
        [ True, False]])

In [181]:
#equal to
i == j

tensor([[False, False],
        [False,  True]])

In [182]:
#not equal to
i != j

tensor([[ True,  True],
        [ True, False]])

###6.Special functions

In [183]:
k = torch.randint(0, 10, (2, 2), dtype=torch.float32)
k

tensor([[5., 4.],
        [8., 8.]])

In [184]:
#log
torch.log(k)

tensor([[1.6094, 1.3863],
        [2.0794, 2.0794]])

In [185]:
#exp
torch.exp(k)

tensor([[ 148.4132,   54.5981],
        [2980.9580, 2980.9580]])

In [186]:
#sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000],
        [2.8284, 2.8284]])

In [187]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820],
        [0.9997, 0.9997]])

In [188]:
#softmax
torch.softmax(k, dim=0)

tensor([[0.0474, 0.0180],
        [0.9526, 0.9820]])

In [189]:
#relu
torch.relu(k)

tensor([[5., 4.],
        [8., 8.]])

#Inplace Operation

In [190]:
m = torch.rand(2, 2)
n = torch.rand(2, 2)
print(m)
print(n)

tensor([[0.5315, 0.1587],
        [0.6542, 0.3278]])
tensor([[0.6532, 0.3958],
        [0.9147, 0.2036]])


In [191]:
m.add_(n)

tensor([[1.1847, 0.5546],
        [1.5689, 0.5315]])

In [192]:
m

tensor([[1.1847, 0.5546],
        [1.5689, 0.5315]])

In [193]:
n

tensor([[0.6532, 0.3958],
        [0.9147, 0.2036]])

In [194]:
torch.relu(m)

tensor([[1.1847, 0.5546],
        [1.5689, 0.5315]])

In [195]:
m.relu_()

tensor([[1.1847, 0.5546],
        [1.5689, 0.5315]])

givee "_" after the name of the operation and that will become inplace operation

In [196]:
m

tensor([[1.1847, 0.5546],
        [1.5689, 0.5315]])

#Copying A Tensor

In [197]:
x = torch.rand(2, 3)

In [198]:
y = x
y

tensor([[0.2018, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [199]:
x[0][0] = 0
x

tensor([[0.0000, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [200]:
y

tensor([[0.0000, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [201]:
id(x)

137835633538832

In [202]:
id(y)

137835633538832

In [203]:
y = x.clone()

In [204]:
x

tensor([[0.0000, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [205]:
y

tensor([[0.0000, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [206]:
x[0][1] = 0
x

tensor([[0.0000, 0.0000, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [207]:
y

tensor([[0.0000, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]])

In [208]:
id(x)

137835633538832

In [209]:
id(y)

137835633535472

#Tensor Operation On GPU

In [210]:
torch.cuda.is_available()

True

In [211]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [212]:
#creating tensor on a GPU
torch.rand(2, 2, device=device)

tensor([[0.6130, 0.0101],
        [0.3984, 0.0403]], device='cuda:0')

In [213]:
#moving an existing tensor to GPU
z = y.to(device)
z

tensor([[0.0000, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874]], device='cuda:0')

In [214]:
z + 5

tensor([[5.0000, 5.2018, 5.9497],
        [5.6666, 5.9811, 5.0874]], device='cuda:0')

#Why GPU?

In [216]:
import time

size = 10000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print("CPU time:", cpu_time)

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print("GPU time:", gpu_time)

print("Speedup:", cpu_time / gpu_time)

CPU time: 16.07127809524536
GPU time: 0.564795970916748
Speedup: 28.455015479588642


#Reshaping Tensors

In [217]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [218]:
#reshape
a.reshape(2, 8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [219]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [222]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.4070, 0.7591, 0.6841, 0.4927],
         [0.3780, 0.6699, 0.4948, 0.7549],
         [0.9056, 0.9051, 0.2189, 0.8444]],

        [[0.6917, 0.8758, 0.2586, 0.1371],
         [0.8997, 0.0655, 0.1780, 0.7144],
         [0.3644, 0.8656, 0.9027, 0.5515]]])

In [224]:
#permute
b.permute(2, 0, 1)

tensor([[[0.4070, 0.3780, 0.9056],
         [0.6917, 0.8997, 0.3644]],

        [[0.7591, 0.6699, 0.9051],
         [0.8758, 0.0655, 0.8656]],

        [[0.6841, 0.4948, 0.2189],
         [0.2586, 0.1780, 0.9027]],

        [[0.4927, 0.7549, 0.8444],
         [0.1371, 0.7144, 0.5515]]])

In [225]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [226]:
c = torch.rand(226, 226, 3)
c

tensor([[[0.4474, 0.1228, 0.9108],
         [0.1583, 0.7434, 0.9051],
         [0.7924, 0.9430, 0.6404],
         ...,
         [0.1725, 0.0672, 0.4272],
         [0.9817, 0.4185, 0.6080],
         [0.0597, 0.7281, 0.8375]],

        [[0.9913, 0.9356, 0.8862],
         [0.3142, 0.8991, 0.9375],
         [0.1466, 0.1505, 0.2398],
         ...,
         [0.4569, 0.2493, 0.2157],
         [0.3202, 0.3345, 0.2530],
         [0.0940, 0.7182, 0.1176]],

        [[0.4555, 0.6907, 0.7539],
         [0.9827, 0.9425, 0.0689],
         [0.8559, 0.0097, 0.7318],
         ...,
         [0.3571, 0.2520, 0.2529],
         [0.1988, 0.7523, 0.8645],
         [0.0303, 0.8739, 0.9494]],

        ...,

        [[0.1206, 0.3260, 0.7224],
         [0.4592, 0.5318, 0.5341],
         [0.3349, 0.0512, 0.0822],
         ...,
         [0.1939, 0.7572, 0.2990],
         [0.3872, 0.6682, 0.4293],
         [0.2715, 0.7076, 0.2856]],

        [[0.2807, 0.8907, 0.9347],
         [0.1458, 0.9983, 0.9207],
         [0.

In [228]:
#unsqueeze
c.unsqueeze(dim=1).shape

torch.Size([226, 1, 226, 3])

In [229]:
d = torch.rand(1, 226, 226, 3)

In [230]:
#squeeze
d.squeeze(dim=0).shape

torch.Size([226, 226, 3])

#NumPy and PyTorch

In [231]:
import numpy as np

In [234]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [237]:
y = x.numpy()
y

array([1, 2, 3])

In [238]:
type(y)

numpy.ndarray

In [241]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [242]:
torch.from_numpy(z)

tensor([1, 2, 3])